doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # To avoid tools like Doctrine Migrations from trying to remove this table because it’s not part of your normal schema
        schema_filter: '~^(?!messenger_messages)~'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
#        metadata_cache_driver: redis
#        query_cache_driver: redis