# Define your clients here. The example below connects to database 0 of the default Redis server.
#
# See https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md for instructions on
# how to configure the bundle.
snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: 'redis://127.0.0.1'
            logging: '%kernel.debug%'
            options:
                replication: sentinel
                service: mymaster  #The service is the name of the set of Redis instances.
        doctrine:
            type: phpredis
            alias: doctrine
            dsn: "redis://127.0.0.1"
            options:
#                profile: 2.8
                prefix: "BantuDico:"
    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default          # the name of your entity_manager connection
            namespace: "metadata_cache:"
        result_cache:
            client: doctrine
            entity_manager: default  # you may specify multiple entity_managers
            namespace: "result_cache:"
        query_cache:
            client: doctrine
            entity_manager: default
            namespace: "query_cache:"