version: '3'

services:
    #  Chaque conteneur commence avec un nom qui lui est propre ; dans notre cas, notre premier conteneur se nommera db
    db:
        image: mysql
        ports:
            - 3306:3306
        # les conteneurs Docker ne sont pas faits pour faire fonctionner des services stateful, et une base de données
        # est par définition un service stateful. Volumes permet de stocker l'ensemble du contenu du dossier/var/lib/mysql
        # dans un disque persistant. Et donc, de pouvoir garder les données en local sur notre host.

        # db_data est un volume créé par Docker directement, qui permet d'écrire les données sur le disque hôte sans spécifier
        # l'emplacement exact. Vous auriez pu aussi faire un /data/mysql:/var/lib/mysql qui serait aussi fonctionnel.
        volumes:
            - db_data:/var/lib/mysql

        # si le serveur MySQL s'arrête, celui-ci  redémarrera automatiquement grâce à l'argument restart: always.
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        env_file:
          - ".env"

    #phpmyadmin est attaché au container « db », et il sera accessible sur le port 8181
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - 8181:80
        # depends_on, nous permet de créer une dépendance entre deux conteneurs. Ainsi, Docker démarrera le service db avant de démarrer le service Wordpress
        depends_on:
            - db
    php:
        build: docker/php # Get our Dockerfile configuration
        links:
            - db:mysqldb
        volumes:
            - ${PROJECT_PATH}:/var/www/html/sango-dico
        ports:
            - 80:80
        env_file:
            - ".env"
volumes:
    db_data: {}